# Nombre del Microservicio (Debe coincidir con el del API Gateway)
spring.application.name=prestamo.multa

# Perfil activo que cargará Spring
spring.profiles.active=dev

# Servidor
server.address=0.0.0.0
# Cambiado a 8082 para que no choque con el puerto 8080 del API Gateway
server.port=8082

# --- CONEXIÓN AL SERVIDOR EUREKA ---
# Indica dónde está el servidor de descubrimiento y que use la IP para comunicarse
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Documentación Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

# Evita errores de serialización con HATEOAS y Jackson
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false