spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

spring.cloud.gateway.routes[0].id=libro-service
spring.cloud.gateway.routes[0].uri=lb://MICROSERVICIOLIBRO
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/libros/**
spring.cloud.gateway.routes[0].filters[0]=name=CircuitBreaker
spring.cloud.gateway.routes[0].filters[0].args.fallbackUri=forward:/fallback/libros

spring.cloud.gateway.routes[1].id=material-service
spring.cloud.gateway.routes[1].uri=lb://MICROSERVICIOLIBRO
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/materiales/**
spring.cloud.gateway.routes[1].filters[0]=name=CircuitBreaker
spring.cloud.gateway.routes[1].filters[0].args.fallbackUri=forward:/fallback/libros

spring.cloud.gateway.routes[2].id=inventario-service
spring.cloud.gateway.routes[2].uri=lb://MICROSERVICIOLIBRO
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/inventarios/**
spring.cloud.gateway.routes[2].filters[0]=name=CircuitBreaker
spring.cloud.gateway.routes[2].filters[0].args.fallbackUri=forward:/fallback/libros

spring.cloud.gateway.routes[3].id=notificacion-service
spring.cloud.gateway.routes[3].uri=lb://NOTIFICACIONMICROSERVICIO
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/notificaciones/**
spring.cloud.gateway.routes[3].filters[0]=name=CircuitBreaker
spring.cloud.gateway.routes[3].filters[0].args.fallbackUri=forward:/fallback/notificaciones

spring.cloud.gateway.routes[4].id=usuario-service
spring.cloud.gateway.routes[4].uri=lb://NOTIFICACIONMICROSERVICIO
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/usuarios/**
spring.cloud.gateway.routes[4].filters[0]=name=CircuitBreaker
spring.cloud.gateway.routes[4].filters[0].args.fallbackUri=forward:/fallback/notificaciones

spring.cloud.gateway.routes[5].id=prestamo-service
spring.cloud.gateway.routes[5].uri=lb://MICROSERVICIOPRESTAMO-MULTA
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/prestamos/**
spring.cloud.gateway.routes[5].filters[0]=name=CircuitBreaker
spring.cloud.gateway.routes[5].filters[0].args.fallbackUri=forward:/fallback/prestamos

spring.cloud.gateway.routes[6].id=multa-service
spring.cloud.gateway.routes[6].uri=lb://MICROSERVICIOPRESTAMO-MULTA
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/v1/multas/**
spring.cloud.gateway.routes[6].filters[0]=name=CircuitBreaker
spring.cloud.gateway.routes[6].filters[0].args.fallbackUri=forward:/fallback/prestamos

spring.cloud.gateway.routes[7].id=prestamo-libro-service
spring.cloud.gateway.routes[7].uri=lb://MICROSERVICIOPRESTAMO-MULTA
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/v1/prestamo-libros/**
spring.cloud.gateway.routes[7].filters[0]=name=CircuitBreaker
spring.cloud.gateway.routes[7].filters[0].args.fallbackUri=forward:/fallback/prestamos

spring.cloud.gateway.routes[8].id=libro-consulta-service
spring.cloud.gateway.routes[8].uri=lb://MICROSERVICIOPRESTAMO-MULTA
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/v1/libros/**
spring.cloud.gateway.routes[8].filters[0]=name=CircuitBreaker
spring.cloud.gateway.routes[8].filters[0].args.fallbackUri=forward:/fallback/prestamos

spring.cloud.gateway.routes[9].id=alquiler-consulta-service
spring.cloud.gateway.routes[9].uri=lb://MICROSERVICIOPRESTAMO-MULTA
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/v1/alquiler/**
spring.cloud.gateway.routes[9].filters[0]=name=CircuitBreaker
spring.cloud.gateway.routes[9].filters[0].args.fallbackUri=forward:/fallback/prestamos

spring.cloud.gateway.routes[10].id=devolucion-consulta-service
spring.cloud.gateway.routes[10].uri=lb://MICROSERVICIOPRESTAMO-MULTA
spring.cloud.gateway.routes[10].predicates[0]=Path=/api/v1/devolucion/**
spring.cloud.gateway.routes[10].filters[0]=name=CircuitBreaker
spring.cloud.gateway.routes[10].filters[0].args.fallbackUri=forward:/fallback/prestamos

spring.cloud.gateway.routes[11].id=eureka-web
spring.cloud.gateway.routes[11].uri=http://${EUREKA_HOST:eureka-server}:8761
spring.cloud.gateway.routes[11].predicates[0]=Path=/eureka/web
spring.cloud.gateway.routes[11].filters[0]=SetPath=/

spring.cloud.gateway.routes[12].id=eureka-other
spring.cloud.gateway.routes[12].uri=http://${EUREKA_HOST:eureka-server}:8761
spring.cloud.gateway.routes[12].predicates[0]=Path=/eureka/**

spring.cloud.gateway.default-filters[0]=name=CircuitBreaker

spring.cloud.circuitbreaker.enabled=true
spring.cloud.circuitbreaker.resilience4j.enabled=true

spring.cloud.loadbalancer.enabled=true
